#!/bin/bash

# Install Your Own TURN Server (Coturn) - No 3rd Party APIs!
# This script installs and configures Coturn on Ubuntu/Debian

echo "========================================="
echo "Installing Coturn TURN Server"
echo "========================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root: sudo bash install-coturn.sh"
    exit 1
fi

# Get public IP
PUBLIC_IP=$(curl -s ifconfig.me)
echo "Detected public IP: $PUBLIC_IP"

# Get user input
read -p "Enter TURN username [default: turnuser]: " TURN_USER
TURN_USER=${TURN_USER:-turnuser}

read -p "Enter TURN password [default: turnpass123]: " TURN_PASS
TURN_PASS=${TURN_PASS:-turnpass123}

read -p "Enter realm/domain [default: $PUBLIC_IP]: " REALM
REALM=${REALM:-$PUBLIC_IP}

echo ""
echo "Configuration:"
echo "  Public IP: $PUBLIC_IP"
echo "  Username: $TURN_USER"
echo "  Password: $TURN_PASS"
echo "  Realm: $REALM"
echo ""
read -p "Continue with installation? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

# Update system
echo "Updating system..."
apt-get update

# Install coturn
echo "Installing coturn..."
apt-get install coturn -y

# Backup original config
cp /etc/turnserver.conf /etc/turnserver.conf.backup

# Create new config
echo "Creating configuration..."
cat > /etc/turnserver.conf << EOF
# Coturn TURN Server Configuration
# Generated by install-coturn.sh

# Listening port
listening-port=3478
tls-listening-port=5349

# External IP
external-ip=$PUBLIC_IP

# Authentication
lt-cred-mech
user=$TURN_USER:$TURN_PASS
realm=$REALM

# Fingerprint
fingerprint

# Logging
verbose
log-file=/var/log/turnserver.log

# Security
no-multicast-peers
no-cli
no-tlsv1
no-tlsv1_1

# Relay ports
min-port=49152
max-port=65535

# Performance
total-quota=100
bps-capacity=0
stale-nonce=600

# Deny private IP ranges from being relayed
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
EOF

# Enable coturn
echo "Enabling coturn..."
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# Configure firewall
echo "Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 3478/tcp
    ufw allow 3478/udp
    ufw allow 5349/tcp
    ufw allow 49152:65535/tcp
    ufw allow 49152:65535/udp
    echo "Firewall rules added"
else
    echo "UFW not found. Please manually open ports:"
    echo "  - 3478 (TCP/UDP)"
    echo "  - 5349 (TCP)"
    echo "  - 49152-65535 (TCP/UDP)"
fi

# Start coturn
echo "Starting coturn..."
systemctl restart coturn
systemctl enable coturn

# Check status
sleep 2
if systemctl is-active --quiet coturn; then
    echo ""
    echo "========================================="
    echo "✓ Coturn installed successfully!"
    echo "========================================="
    echo ""
    echo "Your TURN Server Details:"
    echo "  Server: $PUBLIC_IP:3478"
    echo "  Username: $TURN_USER"
    echo "  Password: $TURN_PASS"
    echo ""
    echo "Add to your webrtc-client.js:"
    echo ""
    echo "  {"
    echo "    urls: 'turn:$PUBLIC_IP:3478',"
    echo "    username: '$TURN_USER',"
    echo "    credential: '$TURN_PASS',"
    echo "  },"
    echo "  {"
    echo "    urls: 'turn:$PUBLIC_IP:3478?transport=tcp',"
    echo "    username: '$TURN_USER',"
    echo "    credential: '$TURN_PASS',"
    echo "  },"
    echo ""
    echo "Check status: sudo systemctl status coturn"
    echo "View logs: sudo tail -f /var/log/turnserver.log"
    echo ""
else
    echo ""
    echo "========================================="
    echo "✗ Coturn failed to start"
    echo "========================================="
    echo "Check logs: sudo journalctl -u coturn -n 50"
    exit 1
fi
